### ISSUE TITLE
Default Zombie character spawns massive groups of sausages

### ISSUE THREAD

**Issue by ilgmesh** [devyndamonster/TakeAndHoldTweaker#36]
Frames tanked when I started a zombie character, massive groups of pale sausages everywhere with broken AI

**Comment by devyndamonster** [comment]
I tried to recreate this on the next version of TNH Tweaker, and didn't have this issue, so fingers crossed I fixed whatever is causing this in the next version. Regardless, if you could send me the log file from BepInEx, I can tell you wether it's TNH Tweaker causing the issue or something else. To get the log file from BepInEx, go to the config folder and enable logging to disk inside the BepInEx config file.

**Comment by ilgmesh** [comment]
> 
> 
> I tried to recreate this on the next version of TNH Tweaker, and didn't have this issue, so fingers crossed I fixed whatever is causing this in the next version. Regardless, if you could send me the log file from BepInEx, I can tell you wether it's TNH Tweaker causing the issue or something else. To get the log file from BepInEx, go to the config folder and enable logging to disk inside the BepInEx config file.

[LogOutput.log](https://github.com/devyndamonster/TakeAndHoldTweaker/files/5669495/LogOutput.log)
Here's my log, hopefully the solution is obvious cause the only troubleshooting I did was removing tnhtweaker which fixed the issue.
I have some good news though, on my second test here my frames didn't drop like they did the first time, but zombies are still broken, as seen here
![20201209172602_1](https://user-images.githubusercontent.com/39890787/101705362-00c48b80-3a44-11eb-8066-983f13b604c9.jpg)

**Comment by devyndamonster** [comment]
That output log doesn't include much, and that might be because it only shows the output log for the most recent launch of the game. Try to run the game and recreate the bug, and then send the output log immediately after that run. That should allow me to see where the error happens

**Comment by ilgmesh** [comment]
That's actually exactly what the log said after seeing the bug, I enabled more logging options in the config this time, hopefully it's enough
[LogOutput.log](https://github.com/devyndamonster/TakeAndHoldTweaker/files/5682358/LogOutput.log)

**Comment by devyndamonster** [comment]
It looks like you might have enabled the harmony logging, which we don't want. Try to set the Bepinex config to match the below images, and then try to log the bug again
![harmony](https://user-images.githubusercontent.com/6070388/102001777-c36e3100-3cc3-11eb-9618-99aac392f16e.PNG)
![bepinex](https://user-images.githubusercontent.com/6070388/102001785-e13b9600-3cc3-11eb-8205-493ad6403b75.PNG)

**Comment by ilgmesh** [comment]
Sorry, I'm not a dev so I had no idea what logs to enable, hopefully this is right. Took me awhile cause I wanted to try it with the updated version first, but I'm getting the same problem
[LogOutput.log](https://github.com/devyndamonster/TakeAndHoldTweaker/files/5703650/LogOutput.log)
